import snapshot from "@/lib/discord-snapshot.json";

/**
 * Static Discord profile card. Values come from lib/discord-snapshot.json,
 * generated by tools/fetch_discord.py — no runtime fetch, no token, no polling.
 */
export function DiscordCard() {
  const { avatar_url, decoration_url, banner_url, banner_color, clan, badges } = snapshot;

  const banner = banner_url
    ? { backgroundImage: `url(${banner_url})` }
    : { background: banner_color ?? "var(--bg3)" };

  return (
    <div className="discord-profile">
      <div className="dp-banner" style={banner} />
      <div className="dp-body">
        <div className="dp-avatar-wrap">
          <div className="dp-avatar-frame">
            <img src={avatar_url} alt={`${snapshot.global_name}'s avatar`} className="dp-avatar-img" />
            {decoration_url && (
              <img src={decoration_url} alt="" className="dp-avatar-decoration" aria-hidden />
            )}
          </div>
        </div>
        <div className="dp-details">
          <span className="dp-name">{snapshot.global_name}</span>
          <span className="dp-username">@{snapshot.username}</span>
          {clan.tag && (
            <span className="dp-clan">
              {clan.badge_url && <img src={clan.badge_url} alt="" loading="lazy" />}
              {clan.tag}
            </span>
          )}
          {badges.length > 0 && (
            <div className="dp-badges">
              {badges.map((b) => (
                <img key={b.name} src={b.icon_url} alt={b.description ?? b.name} title={b.description ?? b.name} loading="lazy" />
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}